source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '7.0'

xcodeproj 'simple-exchange-app'

pod 'LiveSDK'
pod 'ADALIOS', '~> 1.2.2' # 1.2.2 < ver < 1.2.2
pod 'OrcEngine', :git => 'https://github.com/MSOpenTech/orc-for-ios.git', :branch => 'dev'