source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

workspace 'sdk_tests'
xcodeproj 'sdk_tests'

pod 'orc', :git => 'https://github.com/MSOpenTech/orc-for-ios', :branch => 'dev'
pod 'Office365', :path => '../..'
