source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

xcodeproj 'simple-discovery-app'
pod 'orc', '=0.11.0'
pod 'Office365/discovery', :git => 'https://github.com/OfficeDev/Office-365-SDK-for-iOS', :branch => 'master'