/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/


#import "MSGraphFetchers.h"
#import "core/core.h"

@implementation MSGraphDriveItemFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSGraphDriveItem class]]) {

		_operations = [[MSGraphDriveItemOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSGraphDriveItem *driveItem, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSGraphDriveItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSGraphDriveItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSGraphDriveItemFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSGraphDriveItemFetcher *)expand:(NSString *)value {
    [super expand:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSGraphDriveItem *driveItem, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}
- (MSOrcStreamFetcher *)content {

    return [[MSOrcStreamFetcher alloc] initWithUrl:@"content" parent:self];
}

- (MSGraphUserFetcher *)createdByUser {

	 return [[MSGraphUserFetcher alloc] initWithUrl:@"createdByUser" parent:self asClass:[MSGraphUser class]];
}

- (MSGraphUserFetcher *)lastModifiedByUser {

	 return [[MSGraphUserFetcher alloc] initWithUrl:@"lastModifiedByUser" parent:self asClass:[MSGraphUser class]];
}

- (MSGraphPermissionCollectionFetcher *)permissions {

    return [[MSGraphPermissionCollectionFetcher alloc] initWithUrl:@"permissions" parent:self asClass:[MSGraphPermission class]];
}

- (MSGraphPermissionFetcher *)permissionsById:(NSString *)identifier {

    return [[[MSGraphPermissionCollectionFetcher alloc] initWithUrl:@"permissions" parent:self asClass:[MSGraphPermission class]] getById:identifier];

}

- (MSGraphDriveItemCollectionFetcher *)versions {

    return [[MSGraphDriveItemCollectionFetcher alloc] initWithUrl:@"versions" parent:self asClass:[MSGraphDriveItem class]];
}

- (MSGraphDriveItemFetcher *)versionsById:(NSString *)identifier {

    return [[[MSGraphDriveItemCollectionFetcher alloc] initWithUrl:@"versions" parent:self asClass:[MSGraphDriveItem class]] getById:identifier];

}

- (MSGraphDriveItemCollectionFetcher *)children {

    return [[MSGraphDriveItemCollectionFetcher alloc] initWithUrl:@"children" parent:self asClass:[MSGraphDriveItem class]];
}

- (MSGraphDriveItemFetcher *)childrenById:(NSString *)identifier {

    return [[[MSGraphDriveItemCollectionFetcher alloc] initWithUrl:@"children" parent:self asClass:[MSGraphDriveItem class]] getById:identifier];

}

- (MSGraphThumbnailSetCollectionFetcher *)thumbnails {

    return [[MSGraphThumbnailSetCollectionFetcher alloc] initWithUrl:@"thumbnails" parent:self asClass:[MSGraphThumbnailSet class]];
}

- (MSGraphThumbnailSetFetcher *)thumbnailsById:(NSString *)identifier {

    return [[[MSGraphThumbnailSetCollectionFetcher alloc] initWithUrl:@"thumbnails" parent:self asClass:[MSGraphThumbnailSet class]] getById:identifier];

}

@end
