/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/


#ifndef MSGRAPHCLIENT_H
#define MSGRAPHCLIENT_H

#import <orc.h>
#import "MSGraphModels.h"

@class MSGraphDirectoryObjectCollectionFetcher;
@class MSGraphApplicationCollectionFetcher;
@class MSGraphContactCollectionFetcher;
@class MSGraphDeviceConfigurationCollectionFetcher;
@class MSGraphDeviceCollectionFetcher;
@class MSGraphGroupCollectionFetcher;
@class MSGraphDirectoryRoleCollectionFetcher;
@class MSGraphDirectoryRoleTemplateCollectionFetcher;
@class MSGraphServicePrincipalCollectionFetcher;
@class MSGraphTenantDetailCollectionFetcher;
@class MSGraphUserCollectionFetcher;
@class MSGraphOAuth2PermissionGrantCollectionFetcher;
@class MSGraphSubscribedSkuCollectionFetcher;
@class MSGraphDriveCollectionFetcher;

/** Client MSGraphClient
 *
 */
@interface MSGraphClient : MSOrcBaseContainer

- (instancetype)initWithUrl:(NSString *)url  dependencyResolver:(id<MSOrcDependencyResolver>)resolver;
@property (strong, nonatomic, readonly, getter=directoryObjects) MSGraphDirectoryObjectCollectionFetcher *directoryObjects;
@property (strong, nonatomic, readonly, getter=applications) MSGraphApplicationCollectionFetcher *applications;
@property (strong, nonatomic, readonly, getter=contacts) MSGraphContactCollectionFetcher *contacts;
@property (strong, nonatomic, readonly, getter=deviceConfiguration) MSGraphDeviceConfigurationCollectionFetcher *deviceConfiguration;
@property (strong, nonatomic, readonly, getter=devices) MSGraphDeviceCollectionFetcher *devices;
@property (strong, nonatomic, readonly, getter=groups) MSGraphGroupCollectionFetcher *groups;
@property (strong, nonatomic, readonly, getter=directoryRoles) MSGraphDirectoryRoleCollectionFetcher *directoryRoles;
@property (strong, nonatomic, readonly, getter=directoryRoleTemplates) MSGraphDirectoryRoleTemplateCollectionFetcher *directoryRoleTemplates;
@property (strong, nonatomic, readonly, getter=servicePrincipals) MSGraphServicePrincipalCollectionFetcher *servicePrincipals;
@property (strong, nonatomic, readonly, getter=tenantDetails) MSGraphTenantDetailCollectionFetcher *tenantDetails;
@property (strong, nonatomic, readonly, getter=users) MSGraphUserCollectionFetcher *users;
@property (strong, nonatomic, readonly, getter=oauth2PermissionGrants) MSGraphOAuth2PermissionGrantCollectionFetcher *oauth2PermissionGrants;
@property (strong, nonatomic, readonly, getter=subscribedSkus) MSGraphSubscribedSkuCollectionFetcher *subscribedSkus;
@property (strong, nonatomic, readonly, getter=drives) MSGraphDriveCollectionFetcher *drives;
@end

#endif
