/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#ifndef MSGRAPHGROUPFETCHER_H
#define MSGRAPHGROUPFETCHER_H

#import <orc.h>
#import "MSGraphModels.h"
#import "MSOrcEntityFetcher.h"

@class MSGraphProvisioningErrorCollectionFetcher;
@class MSGraphAppRoleAssignmentCollectionFetcher;
@class MSGraphDirectoryObjectCollectionFetcher;
@class MSGraphDirectoryObjectFetcher;
@class MSGraphPhotoFetcher;
@class MSGraphPhotoCollectionFetcher;
@class MSGraphConversationCollectionFetcher;
@class MSGraphConversationThreadCollectionFetcher;
@class MSGraphCalendarFetcher;
@class MSGraphEventCollectionFetcher;
@class MSGraphItemCollectionFetcher;
@class MSGraphAppRoleAssignmentCollectionFetcher;
@class MSGraphDirectoryObjectCollectionFetcher;
@class MSGraphDirectoryObjectFetcher;
@class MSGraphPhotoFetcher;
@class MSGraphPhotoCollectionFetcher;
@class MSGraphConversationCollectionFetcher;
@class MSGraphConversationThreadCollectionFetcher;
@class MSGraphCalendarFetcher;
@class MSGraphEventCollectionFetcher;
@class MSGraphItemCollectionFetcher;
@class MSGraphAppRoleAssignmentFetcher;
@class MSGraphDirectoryObjectFetcher;
@class MSGraphPhotoFetcher;
@class MSGraphConversationFetcher;
@class MSGraphConversationThreadFetcher;
@class MSGraphEventFetcher;
@class MSGraphItemFetcher;
@class MSGraphGroupOperations;


/** MSGraphGroupFetcher
 *
 */
@interface MSGraphGroupFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphGroupOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void)readWithCallback:(void (^)(MSGraphGroup *, MSOrcError *))callback;
- (void)update:(MSGraphGroup *)Group callback:(void (^)(MSGraphGroup *, MSOrcError*))callback ;
- (void)delete:(void(^)(int status, MSOrcError *))callback;
- (MSGraphGroupFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphGroupFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphGroupFetcher *)select:(NSString *)params;
- (MSGraphGroupFetcher *)expand:(NSString *)value;
@property (strong, nonatomic, readonly, getter=appRoleAssignments) MSGraphAppRoleAssignmentCollectionFetcher *appRoleAssignments;

- (MSGraphAppRoleAssignmentFetcher *)appRoleAssignmentsById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=members) MSGraphDirectoryObjectCollectionFetcher *members;

- (MSGraphDirectoryObjectFetcher *)membersById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=memberOf) MSGraphDirectoryObjectCollectionFetcher *memberOf;

- (MSGraphDirectoryObjectFetcher *)memberOfById:(NSString*)identifier;


@property (strong, nonatomic, readonly, getter=createdOnBehalfOf) MSGraphDirectoryObjectFetcher *createdOnBehalfOf;
@property (strong, nonatomic, readonly, getter=owners) MSGraphDirectoryObjectCollectionFetcher *owners;

- (MSGraphDirectoryObjectFetcher *)ownersById:(NSString*)identifier;


@property (strong, nonatomic, readonly, getter=groupPhoto) MSGraphPhotoFetcher *groupPhoto;
@property (strong, nonatomic, readonly, getter=groupPhotos) MSGraphPhotoCollectionFetcher *groupPhotos;

- (MSGraphPhotoFetcher *)groupPhotosById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=conversations) MSGraphConversationCollectionFetcher *conversations;

- (MSGraphConversationFetcher *)conversationsById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=threads) MSGraphConversationThreadCollectionFetcher *threads;

- (MSGraphConversationThreadFetcher *)threadsById:(NSString*)identifier;


@property (strong, nonatomic, readonly, getter=calendar) MSGraphCalendarFetcher *calendar;
@property (strong, nonatomic, readonly, getter=events) MSGraphEventCollectionFetcher *events;

- (MSGraphEventFetcher *)eventsById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=calendarView) MSGraphEventCollectionFetcher *calendarView;

- (MSGraphEventFetcher *)calendarViewById:(NSString*)identifier;

@property (strong, nonatomic, readonly, getter=files) MSGraphItemCollectionFetcher *files;

- (MSGraphItemFetcher *)filesById:(NSString*)identifier;


@end

#endif
