source 'https://github.com/Cocoapods/Specs.git'

# target :default
platform :ios, '8.0'
workspace 'all_services'
xcodeproj 'outlook_services/outlook_services'

# This is the only way to link with each project/SDK.
# 'outlook_services', 'directory_services', 'discovery_services', 'office365_files_sdk', 'office365_graph_sdk', 'office365_onenote_sdk'

target :outlook_services do
  xcodeproj 'outlook_services/outlook_services'
  pod 'orc', '=0.10.0'
end

target :directory_services do
  xcodeproj 'directory_services/directory_services'
  pod 'orc', '=0.10.0'
end

target :discovery_services do
  xcodeproj 'discovery_services/discovery_services'
  pod 'orc', '=0.10.0'
end

target :office365_files_sdk do
  xcodeproj 'office365_files_sdk/office365_files_sdk'
  pod 'orc', '=0.10.0'
end

target :office365_graph_sdk do
  xcodeproj 'office365_graph_sdk/office365_graph_sdk'
  pod 'orc', '=0.10.0'
end

target :office365_onenote_sdk do
  xcodeproj 'office365_onenote_sdk/office365_onenote_sdk'
  pod 'orc', '=0.10.0'
end
