source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

workspace 'all_services'
xcodeproj 'outlook_services/outlook_services'
xcodeproj 'office365_directory_sdk/office365_directory_sdk'
xcodeproj 'office365_discovery_sdk/office365_discovery_sdk'
xcodeproj 'office365_files_sdk/office365_files_sdk'
xcodeproj 'office365_graph_sdk/office365_graph_sdk'
xcodeproj 'office365_onenote_sdk/office365_onenote_sdk'

pod 'orc', '=0.10.0'
