/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#ifndef MSONENOTENOTEBOOKFETCHER_H
#define MSONENOTENOTEBOOKFETCHER_H

#import "MSOneNoteModels.h"
#import "api/api.h"
#import "core/core.h"
#import "core/MSOrcEntityFetcher.h"

@class MSOneNoteNotebookLinksFetcher;
@class MSOneNoteIdentitySetFetcher;
@class MSOneNoteSectionCollectionFetcher;
@class MSOneNoteSectionGroupCollectionFetcher;
@class MSOneNoteSectionCollectionFetcher;
@class MSOneNoteSectionGroupCollectionFetcher;
@class MSOneNoteSectionFetcher;
@class MSOneNoteSectionGroupFetcher;
@class MSOneNoteNotebookOperations;


/** MSOneNoteNotebookFetcher
 *
 */
@interface MSOneNoteNotebookFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSOneNoteNotebookOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void)readWithCallback:(void (^)(MSOneNoteNotebook *, MSOrcError *))callback;
- (void)update:(MSOneNoteNotebook *)Notebook callback:(void (^)(MSOneNoteNotebook *, MSOrcError*))callback ;
- (void)delete:(void(^)(int status, MSOrcError *))callback;
- (MSOneNoteNotebookFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSOneNoteNotebookFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSOneNoteNotebookFetcher *)select:(NSString *)params;
- (MSOneNoteNotebookFetcher *)expand:(NSString *)value;
@property (strong, nonatomic, readonly, getter=sections) MSOneNoteSectionCollectionFetcher *sections;

- (MSOneNoteSectionFetcher *)sectionsById:(id)identifier;

@property (strong, nonatomic, readonly, getter=sectionGroups) MSOneNoteSectionGroupCollectionFetcher *sectionGroups;

- (MSOneNoteSectionGroupFetcher *)sectionGroupsById:(id)identifier;


@end

#endif
