/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#ifndef MSSAMPLESERVICESAMPLEENTITYFETCHER_H
#define MSSAMPLESERVICESAMPLEENTITYFETCHER_H

#import "MSSampleServiceModels.h"
#import "api/api.h"
#import "core/core.h"
#import "core/MSOrcEntityFetcher.h"

@class MSSampleServiceAnotherEntityCollectionFetcher;
@class MSSampleServiceItemCollectionFetcher;
@class MSSampleServiceAnotherEntityCollectionFetcher;
@class MSSampleServiceItemCollectionFetcher;
@class MSSampleServiceAnotherEntityFetcher;
@class MSSampleServiceItemFetcher;
@class MSSampleServiceSampleEntityFetcher;
@class MSSampleServiceSampleEntityOperations;


/** MSSampleServiceSampleEntityFetcher
 *
 */
@interface MSSampleServiceSampleEntityFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSSampleServiceSampleEntityOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void)readWithCallback:(void (^)(MSSampleServiceSampleEntity *, MSOrcError *))callback;
- (void)update:(MSSampleServiceSampleEntity *)SampleEntity callback:(void (^)(MSSampleServiceSampleEntity *, MSOrcError*))callback ;
- (void)delete:(void(^)(int status, MSOrcError *))callback;
- (MSSampleServiceSampleEntityFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSSampleServiceSampleEntityFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSSampleServiceSampleEntityFetcher *)select:(NSString *)params;
- (MSSampleServiceSampleEntityFetcher *)expand:(NSString *)value;
@property (strong, nonatomic, readonly, getter=content) MSOrcStreamFetcher *content;

@property (strong, nonatomic, readonly, getter=nestedSampleEntity) MSSampleServiceSampleEntityFetcher *nestedSampleEntity;
@property (strong, nonatomic, readonly, getter=navigations) MSSampleServiceAnotherEntityCollectionFetcher *navigations;

- (MSSampleServiceAnotherEntityFetcher *)navigationsById:(id)identifier;

@property (strong, nonatomic, readonly, getter=items) MSSampleServiceItemCollectionFetcher *items;

- (MSSampleServiceItemFetcher *)itemsById:(id)identifier;

@property (strong, nonatomic, readonly, getter=nestedSampleEntityCollection) MSSampleServiceSampleEntityCollectionFetcher *nestedSampleEntityCollection;

- (MSSampleServiceSampleEntityFetcher *)nestedSampleEntityCollectionById:(id)identifier;


@end

#endif
