/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#import "MSDirectoryServicesModels.h"
#import "core/MSOrcObjectizer.h"


/** Implementation for MSDirectoryServicesRequiredResourceAccess
 *
 */
@implementation MSDirectoryServicesRequiredResourceAccess


@synthesize odataType = _odataType;

+ (NSDictionary *) $$$_$$$propertiesNamesMappings
{
    static NSDictionary *_$$$_$$$propertiesNamesMappings=nil; 
    
    if(_$$$_$$$propertiesNamesMappings==nil){
    _$$$_$$$propertiesNamesMappings=[[NSDictionary alloc] initWithObjectsAndKeys:  @"resourceAppId", @"resourceAppId", @"resourceAccess", @"resourceAccess", nil];
    
    }
    
    return _$$$_$$$propertiesNamesMappings;
}


- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.DirectoryServices.RequiredResourceAccess";

        
		_resourceAccess = [[NSMutableArray alloc] initWithCollectionType:@"NSMutableArray"];
    }

	return self;
}


- (instancetype) initWithDictionary: (NSDictionary *) dic {
    if((self = [self init])) {
    
		_resourceAppId = [dic objectForKey: @"resourceAppId"] != nil ? [[dic objectForKey: @"resourceAppId"] copy] : _resourceAppId;

        if([dic objectForKey: @"resourceAccess"] != [NSNull null]){
            _resourceAccess = [NSMutableArray arrayWithCapacity:[[dic objectForKey: @"resourceAccess"] count]];
            
            for (id object in [dic objectForKey: @"resourceAccess"]) {
                [_resourceAccess addObject:[[MSDirectoryServicesResourceAccess alloc] initWithDictionary: object]];
            }
        }
        

    }
    
    return self;
}

- (NSDictionary *) toDictionary {
    return [[NSDictionary alloc] initWithObjectsAndKeys: 
    		 [_resourceAppId copy], @"resourceAppId",
		 [[NSMutableArray alloc] init], @"resourceAccess",
            nil];
}


/** Setter implementation for property resourceAppId
 *
 */
- (void) setResourceAppId: (NSString *) value {
    _resourceAppId = value;
    [self valueChangedFor:@"resourceAppId"];
}
       
/** Setter implementation for property resourceAccess
 *
 */
- (void) setResourceAccess: (NSMutableArray *) value {
    _resourceAccess = value;
    [self valueChangedFor:@"resourceAccess"];
}
       

@end
