/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#import "MSDirectoryServicesModels.h"



/** Implementation for MSDirectoryServicesDirectoryLinkChange
 *
 */
@implementation MSDirectoryServicesDirectoryLinkChange


@synthesize odataType = _odataType;


+ (NSDictionary *) $$$_$$$propertiesNamesMappings
{
    static NSDictionary *_$$$_$$$propertiesNamesMappings=nil; 
    
    if(_$$$_$$$propertiesNamesMappings==nil){
    _$$$_$$$propertiesNamesMappings=[[NSDictionary alloc] initWithObjectsAndKeys:  @"associationType", @"associationType", @"sourceObjectId", @"sourceObjectId", @"sourceObjectType", @"sourceObjectType", @"sourceObjectUri", @"sourceObjectUri", @"targetObjectId", @"targetObjectId", @"targetObjectType", @"targetObjectType", @"targetObjectUri", @"targetObjectUri", @"objectType", @"objectType", @"objectId", @"objectId", @"deletionTimestamp", @"deletionTimestamp", @"createdOnBehalfOf", @"createdOnBehalfOf", @"createdObjects", @"createdObjects", @"manager", @"manager", @"directReports", @"directReports", @"members", @"members", @"memberOf", @"memberOf", @"owners", @"owners", @"ownedObjects", @"ownedObjects", nil];
    
    }
    
    return _$$$_$$$propertiesNamesMappings;
}

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.DirectoryServices.DirectoryLinkChange";
        
        
    }

	return self;
}



- (instancetype) initWithDictionary: (NSDictionary *) dic {
    if((self = [self init])) {
    
		_associationType = [dic objectForKey: @"associationType"] != nil ? [[dic objectForKey: @"associationType"] copy] : _associationType;
		_sourceObjectId = [dic objectForKey: @"sourceObjectId"] != nil ? [[dic objectForKey: @"sourceObjectId"] copy] : _sourceObjectId;
		_sourceObjectType = [dic objectForKey: @"sourceObjectType"] != nil ? [[dic objectForKey: @"sourceObjectType"] copy] : _sourceObjectType;
		_sourceObjectUri = [dic objectForKey: @"sourceObjectUri"] != nil ? [[dic objectForKey: @"sourceObjectUri"] copy] : _sourceObjectUri;
		_targetObjectId = [dic objectForKey: @"targetObjectId"] != nil ? [[dic objectForKey: @"targetObjectId"] copy] : _targetObjectId;
		_targetObjectType = [dic objectForKey: @"targetObjectType"] != nil ? [[dic objectForKey: @"targetObjectType"] copy] : _targetObjectType;
		_targetObjectUri = [dic objectForKey: @"targetObjectUri"] != nil ? [[dic objectForKey: @"targetObjectUri"] copy] : _targetObjectUri;

    }
    
    return self;
}

- (NSDictionary *) toDictionary {
    return [[NSDictionary alloc] initWithObjectsAndKeys: 
    		 [_associationType copy], @"associationType",
		 [_sourceObjectId copy], @"sourceObjectId",
		 [_sourceObjectType copy], @"sourceObjectType",
		 [_sourceObjectUri copy], @"sourceObjectUri",
		 [_targetObjectId copy], @"targetObjectId",
		 [_targetObjectType copy], @"targetObjectType",
		 [_targetObjectUri copy], @"targetObjectUri",
            nil];
}


/** Setter implementation for property associationType
 *
 */
- (void) setAssociationType: (NSString *) value {
    _associationType = value;
    [self valueChangedFor:@"associationType"];
}
       
/** Setter implementation for property sourceObjectId
 *
 */
- (void) setSourceObjectId: (NSString *) value {
    _sourceObjectId = value;
    [self valueChangedFor:@"sourceObjectId"];
}
       
/** Setter implementation for property sourceObjectType
 *
 */
- (void) setSourceObjectType: (NSString *) value {
    _sourceObjectType = value;
    [self valueChangedFor:@"sourceObjectType"];
}
       
/** Setter implementation for property sourceObjectUri
 *
 */
- (void) setSourceObjectUri: (NSString *) value {
    _sourceObjectUri = value;
    [self valueChangedFor:@"sourceObjectUri"];
}
       
/** Setter implementation for property targetObjectId
 *
 */
- (void) setTargetObjectId: (NSString *) value {
    _targetObjectId = value;
    [self valueChangedFor:@"targetObjectId"];
}
       
/** Setter implementation for property targetObjectType
 *
 */
- (void) setTargetObjectType: (NSString *) value {
    _targetObjectType = value;
    [self valueChangedFor:@"targetObjectType"];
}
       
/** Setter implementation for property targetObjectUri
 *
 */
- (void) setTargetObjectUri: (NSString *) value {
    _targetObjectUri = value;
    [self valueChangedFor:@"targetObjectUri"];
}
       

@end
