/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/


#ifndef MSDIRECTORYSERVICESSERVICEPRINCIPAL_H
#define MSDIRECTORYSERVICESSERVICEPRINCIPAL_H

#import <Foundation/Foundation.h>
#import "core/MSOrcChangesTrackingArray.h"

@class MSDirectoryServicesAppRole;
@class MSDirectoryServicesKeyCredential;
@class MSDirectoryServicesOAuth2Permission;
@class MSDirectoryServicesPasswordCredential;
@class MSDirectoryServicesAppRoleAssignment;
@class MSDirectoryServicesOAuth2PermissionGrant;
#import "MSDirectoryServicesDirectoryObject.h"
#import "api/MSOrcInteroperableWithDictionary.h"

/** Interface MSDirectoryServicesServicePrincipal
 *
 */
@interface MSDirectoryServicesServicePrincipal : MSDirectoryServicesDirectoryObject <MSOrcInteroperableWithDictionary>

/** Property accountEnabled
 *
 */
@property (nonatomic,  setter=setAccountEnabled:, getter=accountEnabled) bool accountEnabled;

/** Property appDisplayName
 *
 */
@property (nonatomic,  copy, setter=setAppDisplayName:, getter=appDisplayName) NSString * appDisplayName;

/** Property appId
 *
 */
@property (nonatomic,  copy, setter=setAppId:, getter=appId) NSString * appId;

/** Property appOwnerTenantId
 *
 */
@property (nonatomic,  copy, setter=setAppOwnerTenantId:, getter=appOwnerTenantId) NSString * appOwnerTenantId;

/** Property appRoleAssignmentRequired
 *
 */
@property (nonatomic,  setter=setAppRoleAssignmentRequired:, getter=appRoleAssignmentRequired) bool appRoleAssignmentRequired;

/** Property appRoles
 *
 */
@property (nonatomic,  copy, setter=setAppRoles:, getter=appRoles) NSMutableArray * appRoles;

/** Property displayName
 *
 */
@property (nonatomic,  copy, setter=setDisplayName:, getter=displayName) NSString * displayName;

/** Property errorUrl
 *
 */
@property (nonatomic,  copy, setter=setErrorUrl:, getter=errorUrl) NSString * errorUrl;

/** Property homepage
 *
 */
@property (nonatomic,  copy, setter=setHomepage:, getter=homepage) NSString * homepage;

/** Property keyCredentials
 *
 */
@property (nonatomic,  copy, setter=setKeyCredentials:, getter=keyCredentials) NSMutableArray * keyCredentials;

/** Property logoutUrl
 *
 */
@property (nonatomic,  copy, setter=setLogoutUrl:, getter=logoutUrl) NSString * logoutUrl;

/** Property oauth2Permissions
 *
 */
@property (nonatomic,  copy, setter=setOauth2Permissions:, getter=oauth2Permissions) NSMutableArray * oauth2Permissions;

/** Property passwordCredentials
 *
 */
@property (nonatomic,  copy, setter=setPasswordCredentials:, getter=passwordCredentials) NSMutableArray * passwordCredentials;

/** Property preferredTokenSigningKeyThumbprint
 *
 */
@property (nonatomic,  copy, setter=setPreferredTokenSigningKeyThumbprint:, getter=preferredTokenSigningKeyThumbprint) NSString * preferredTokenSigningKeyThumbprint;

/** Property publisherName
 *
 */
@property (nonatomic,  copy, setter=setPublisherName:, getter=publisherName) NSString * publisherName;

/** Property replyUrls
 *
 */
@property (nonatomic,  copy, setter=setReplyUrls:, getter=replyUrls) NSMutableArray * replyUrls;

/** Property samlMetadataUrl
 *
 */
@property (nonatomic,  copy, setter=setSamlMetadataUrl:, getter=samlMetadataUrl) NSString * samlMetadataUrl;

/** Property servicePrincipalNames
 *
 */
@property (nonatomic,  copy, setter=setServicePrincipalNames:, getter=servicePrincipalNames) NSMutableArray * servicePrincipalNames;

/** Property tags
 *
 */
@property (nonatomic,  copy, setter=setTags:, getter=tags) NSMutableArray * tags;

/** Property appRoleAssignedTo
 *
 */
@property (nonatomic,  copy, setter=setAppRoleAssignedTo:, getter=appRoleAssignedTo) NSMutableArray * appRoleAssignedTo;

/** Property appRoleAssignments
 *
 */
@property (nonatomic,  copy, setter=setAppRoleAssignments:, getter=appRoleAssignments) NSMutableArray * appRoleAssignments;

/** Property oauth2PermissionGrants
 *
 */
@property (nonatomic,  copy, setter=setOauth2PermissionGrants:, getter=oauth2PermissionGrants) NSMutableArray * oauth2PermissionGrants;


+ (NSDictionary *) $$$_$$$propertiesNamesMappings;


@end

#endif
