/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/


#ifndef MSDIRECTORYSERVICESDIRECTORYOBJECT_H
#define MSDIRECTORYSERVICESDIRECTORYOBJECT_H

#import <Foundation/Foundation.h>
#import "core/MSOrcChangesTrackingArray.h"

#import "core/MSOrcBaseEntity.h"
#import "api/MSOrcInteroperableWithDictionary.h"

/** Interface MSDirectoryServicesDirectoryObject
 *
 */
@interface MSDirectoryServicesDirectoryObject : MSOrcBaseEntity <MSOrcInteroperableWithDictionary>

/** Property objectType
 *
 */
@property (nonatomic,  copy, setter=setObjectType:, getter=objectType) NSString * objectType;

/** Property objectId
 *
 */
@property (nonatomic,  copy, setter=setObjectId:, getter=objectId) NSString * objectId;

/** Property deletionTimestamp
 *
 */
@property (nonatomic,  copy, setter=setDeletionTimestamp:, getter=deletionTimestamp) NSDate * deletionTimestamp;

/** Property createdOnBehalfOf
 *
 */
@property (nonatomic,  copy, setter=setCreatedOnBehalfOf:, getter=createdOnBehalfOf) MSDirectoryServicesDirectoryObject * createdOnBehalfOf;

/** Property createdObjects
 *
 */
@property (nonatomic,  copy, setter=setCreatedObjects:, getter=createdObjects) NSMutableArray * createdObjects;

/** Property manager
 *
 */
@property (nonatomic,  copy, setter=setManager:, getter=manager) MSDirectoryServicesDirectoryObject * manager;

/** Property directReports
 *
 */
@property (nonatomic,  copy, setter=setDirectReports:, getter=directReports) NSMutableArray * directReports;

/** Property members
 *
 */
@property (nonatomic,  copy, setter=setMembers:, getter=members) NSMutableArray * members;

/** Property memberOf
 *
 */
@property (nonatomic,  copy, setter=setMemberOf:, getter=memberOf) NSMutableArray * memberOf;

/** Property owners
 *
 */
@property (nonatomic,  copy, setter=setOwners:, getter=owners) NSMutableArray * owners;

/** Property ownedObjects
 *
 */
@property (nonatomic,  copy, setter=setOwnedObjects:, getter=ownedObjects) NSMutableArray * ownedObjects;


+ (NSDictionary *) $$$_$$$propertiesNamesMappings;


@end

#endif
