source 'https://github.com/Cocoapods/Specs.git'

# target :default
platform :ios, '8.0'
workspace 'all_services'
xcodeproj 'outlook_services/outlook_services'

# This is the only way to link with each project/SDK.
# 'outlook_services', 'directory_services', 'discovery_services', 'files_services', 'unified_services', 'onenote_services'

target :outlook_services do
  xcodeproj 'outlook_services/outlook_services'
  pod 'orc', '=0.10.0'
end

target :directory_services do
  xcodeproj 'directory_services/directory_services'
  pod 'orc', '=0.10.0'
end

target :discovery_services do
  xcodeproj 'discovery_services/discovery_services'
  pod 'orc', '=0.10.0'
end

target :files_services do
  xcodeproj 'files_services/files_services'
  pod 'orc', '=0.10.0'
end

target :unified_services do
  xcodeproj 'unified_services/unified_services'
  pod 'orc', '=0.10.0'
end

target :onenote_services do
  xcodeproj 'onenote_services/onenote_services'
  pod 'orc', '=0.10.0'
end
