
source 'https://github.com/Cocoapods/Specs.git'

# target :default
platform :ios, '8.0'
workspace 'all_services'

xcodeproj 'DirectoryServices/DirectoryServices'
target :DirectoryServices do
xcodeproj 'DirectoryServices/DirectoryServices'
pod 'orc', '=0.11.0'
end
target :Discovery do
xcodeproj 'Discovery/Discovery'
pod 'orc', '=0.11.0'
end
target :Files do
xcodeproj 'Files/Files'
pod 'orc', '=0.11.0'
end
target :Files do
xcodeproj 'Files/Files'
pod 'orc', '=0.11.0'
end
target :Graph do
xcodeproj 'Graph/Graph'
pod 'orc', '=0.11.0'
end
target :OneNote do
xcodeproj 'OneNote/OneNote'
pod 'orc', '=0.11.0'
end
target :Outlook do
xcodeproj 'Outlook/Outlook'
pod 'orc', '=0.11.0'
end
target :SampleService do
xcodeproj 'SampleService/SampleService'
pod 'orc', '=0.11.0'
end
