source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

xcodeproj 'simple-drive-app'
pod 'LiveSDK'
pod 'ADALIOS', '~> 1.2.2' # 1.2.2 < ver < 1.2.2
pod 'OrcEngine/Implementation', :git => 'https://github.com/MSOpenTech/orc-for-ios.git', :branch => 'dev'
pod 'Office365/Files', :git => 'https://github.com/greathansen/Office-365-SDK-for-iOS', :branch => 'orc-poc'