source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

xcodeproj 'simple-drive-app'
pod 'ADALIOS', '~> 1.2.2' # 1.2.2 < ver < 1.2.2
pod 'Office365/Files', :git => 'https://github.com/MSOpenTech/Office-365-SDK-for-iOS', :branch => 'dev'
