/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#import "MSGraphModels.h"
#import "core/MSOrcObjectizer.h"


/** Implementation for MSGraphAttendeeAvailability
 *
 */
@implementation MSGraphAttendeeAvailability


@synthesize odataType = _odataType;

+ (NSDictionary *) $$$_$$$propertiesNamesMappings
{
    static NSDictionary *_$$$_$$$propertiesNamesMappings=nil; 

        if(_$$$_$$$propertiesNamesMappings==nil) {
    
        _$$$_$$$propertiesNamesMappings=[[NSDictionary alloc] initWithObjectsAndKeys:  @"Attendee", @"attendee", @"Availability", @"availability", nil];
        
    }
    
    return _$$$_$$$propertiesNamesMappings;
}


- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#microsoft.graph.AttendeeAvailability";

    }

	return self;
}


- (instancetype) initWithDictionary: (NSDictionary *) dic {
    if((self = [self init])) {
        if(dic!=nil) {
		_attendee = (![dic objectForKey: @"Attendee"] || [ [dic objectForKey: @"Attendee"] isKindOfClass:[NSNull class]] )?_attendee:[[MSGraphAttendeeBase alloc] initWithDictionary: [dic objectForKey: @"Attendee"]];
		_availability = (![dic objectForKey: @"Availability"] || [ [dic objectForKey: @"Availability"] isKindOfClass:[NSNull class]] )?_availability:[MSGraphFreeBusyStatusSerializer fromString:[dic objectForKey: @"Availability"]];
    }
    [self.updatedValues removeAllObjects];
    }
    
    return self;
}

- (NSDictionary *) toDictionary {
    
    NSMutableDictionary *dic=[[NSMutableDictionary alloc] init];

	{id curVal = [self.attendee toDictionary];if (curVal!=nil) [dic setValue: curVal forKey: @"Attendee"];}
	{[dic setValue: [MSGraphFreeBusyStatusSerializer toString:self.availability] forKey: @"Availability"];}
    [dic setValue: @"#microsoft.graph.AttendeeAvailability" forKey: @"@odata.type"];

    return dic;
}

- (NSDictionary *) toUpdatedValuesDictionary {
    
    NSMutableDictionary *dic=[[NSMutableDictionary alloc] init];

	{id curVal = self.attendee;
    if([self.updatedValues containsObject:@"Attendee"])
    {
                [dic setValue: curVal==nil?[NSNull null]:[curVal toDictionary] forKey: @"Attendee"];
            }
        else
    {
                
        NSDictionary *updatedDic=[curVal toUpdatedValuesDictionary];
        
            if(updatedDic!=nil && [updatedDic count]>0)
            {
                [dic setValue: [curVal toDictionary] forKey: @"Attendee"];
            }
        
            }}
 if([self.updatedValues containsObject:@"Availability"])
            { [dic setValue: [MSGraphFreeBusyStatusSerializer toString:self.availability] forKey: @"Availability"];
}    return dic;
}


/** Setter implementation for property attendee
 *
 */
- (void) setAttendee: (MSGraphAttendeeBase *) value {
    _attendee = value;
    [self valueChangedFor:@"Attendee"];
}
       
/** Setter implementation for property availability
 *
 */
- (void) setAvailability: (MSGraphFreeBusyStatus) value {
    _availability = value;
    [self valueChangedFor:@"Availability"];
}
       

- (void)setAvailabilityString:(NSString *)string {
        
    _availability = [MSGraphFreeBusyStatusSerializer fromString:string];
    [self valueChangedFor:@"Availability"]; 
}


@end
