/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/


#ifndef MSGRAPHCONVERSATIONTHREAD_H
#define MSGRAPHCONVERSATIONTHREAD_H

#import <Foundation/Foundation.h>

@class MSGraphRecipient;
@class MSGraphPost;
#import "MSOrcBaseEntity.h"

/** Interface MSGraphConversationThread
 *
 */
@interface MSGraphConversationThread : MSOrcBaseEntity

/** Property _id
 *
 */
@property (nonatomic,  copy, setter=setId:, getter=_id) NSString * _id;

/** Property toRecipients
 *
 */
@property (nonatomic,  copy, setter=setToRecipients:, getter=toRecipients) NSMutableArray * toRecipients;

/** Property ccRecipients
 *
 */
@property (nonatomic,  copy, setter=setCcRecipients:, getter=ccRecipients) NSMutableArray * ccRecipients;

/** Property preview
 *
 */
@property (nonatomic,  copy, setter=setPreview:, getter=preview) NSString * preview;

/** Property posts
 *
 */
@property (nonatomic,  copy, setter=setPosts:, getter=posts) NSMutableArray * posts;


+ (NSDictionary *) $$$_$$$propertiesNamesMappings;


@end

#endif
