/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/



#import "MSGraphModels.h"



/** Implementation for MSGraphItem
 *
 */
@implementation MSGraphItem


@synthesize odataType = _odataType;


+ (NSDictionary *) $$$_$$$propertiesNamesMappings
{
    static NSDictionary *_$$$_$$$propertiesNamesMappings=nil; 
    
    if(_$$$_$$$propertiesNamesMappings==nil){
    _$$$_$$$propertiesNamesMappings=[[NSDictionary alloc] initWithObjectsAndKeys:  @"createdBy", @"createdBy", @"eTag", @"eTag", @"id", @"_id", @"lastModifiedBy", @"lastModifiedBy", @"name", @"name", @"parentReference", @"parentReference", @"size", @"size", @"dateTimeCreated", @"dateTimeCreated", @"dateTimeLastModified", @"dateTimeLastModified", @"type", @"type", @"webUrl", @"webUrl", @"createdByUser", @"createdByUser", @"lastModifiedByUser", @"lastModifiedByUser", @"children", @"children", nil];
    
    }
    
    return _$$$_$$$propertiesNamesMappings;
}

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.Graph.Item";
        
        
		_children = [[NSMutableArray alloc] initWithCollectionType:@"NSMutableArray"];
    }

	return self;
}

/** Setter implementation for property createdBy
 *
 */
- (void) setCreatedBy: (MSGraphIdentitySet *) value {
    _createdBy = value;
    [self valueChanged:_createdBy forProperty:@"createdBy"];
}
       
/** Setter implementation for property eTag
 *
 */
- (void) setETag: (NSString *) value {
    _eTag = value;
    [self valueChanged:_eTag forProperty:@"eTag"];
}
       
/** Setter implementation for property _id
 *
 */
- (void) setId: (NSString *) value {
    __id = value;
    [self valueChanged:__id forProperty:@"id"];
}
       
/** Setter implementation for property lastModifiedBy
 *
 */
- (void) setLastModifiedBy: (MSGraphIdentitySet *) value {
    _lastModifiedBy = value;
    [self valueChanged:_lastModifiedBy forProperty:@"lastModifiedBy"];
}
       
/** Setter implementation for property name
 *
 */
- (void) setName: (NSString *) value {
    _name = value;
    [self valueChanged:_name forProperty:@"name"];
}
       
/** Setter implementation for property parentReference
 *
 */
- (void) setParentReference: (MSGraphItemReference *) value {
    _parentReference = value;
    [self valueChanged:_parentReference forProperty:@"parentReference"];
}
       
/** Setter implementation for property size
 *
 */
- (void) setSize: (int) value {
    _size = value;
    [self valueChangedForInt:_size forProperty:@"size"];
}
       
/** Setter implementation for property dateTimeCreated
 *
 */
- (void) setDateTimeCreated: (NSDate *) value {
    _dateTimeCreated = value;
    [self valueChanged:_dateTimeCreated forProperty:@"dateTimeCreated"];
}
       
/** Setter implementation for property dateTimeLastModified
 *
 */
- (void) setDateTimeLastModified: (NSDate *) value {
    _dateTimeLastModified = value;
    [self valueChanged:_dateTimeLastModified forProperty:@"dateTimeLastModified"];
}
       
/** Setter implementation for property type
 *
 */
- (void) setType: (NSString *) value {
    _type = value;
    [self valueChanged:_type forProperty:@"type"];
}
       
/** Setter implementation for property webUrl
 *
 */
- (void) setWebUrl: (NSString *) value {
    _webUrl = value;
    [self valueChanged:_webUrl forProperty:@"webUrl"];
}
       
/** Setter implementation for property createdByUser
 *
 */
- (void) setCreatedByUser: (MSGraphUser *) value {
    _createdByUser = value;
    [self valueChanged:_createdByUser forProperty:@"createdByUser"];
}
       
/** Setter implementation for property lastModifiedByUser
 *
 */
- (void) setLastModifiedByUser: (MSGraphUser *) value {
    _lastModifiedByUser = value;
    [self valueChanged:_lastModifiedByUser forProperty:@"lastModifiedByUser"];
}
       
/** Setter implementation for property children
 *
 */
- (void) setChildren: (NSMutableArray *) value {
    _children = value;
    [self valueChanged:_children forProperty:@"children"];
}
       

@end
